version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard-test-c
    image: dashboard-test:1.0
    ports:
      - '3000:3000'
    env_file:
      - ./.env
